export type PermissionCode = string;

export const PERMISSION_CODES = {
  // ── HOME ──────────────────────────────────────────────────────────
  HOME_VIEW: 'HOME_VIEW',

  // ── ORGANIZATION ──────────────────────────────────────────
  ORG_VIEW: 'ORGANIZATION_VIEW',
  ORG_MANAGE: 'ORGANIZATION_MANAGE',

  // ORGANIZATION - COMPANY
  ORG_COMPANY_VIEW: 'ORGANIZATION_COMPANY_VIEW',
  ORG_COMPANY_MANAGE: 'ORGANIZATION_COMPANY_MANAGE',
  ORG_COMPANY_CREATE: 'ORGANIZATION_COMPANY_CREATE',
  ORG_COMPANY_UPDATE: 'ORGANIZATION_COMPANY_UPDATE',
  ORG_COMPANY_DEACTIVATE: 'ORGANIZATION_COMPANY_DEACTIVATE',
  ORG_COMPANY_ACTIVATE: 'ORGANIZATION_COMPANY_ACTIVATE',
  ORG_COMPANY_IMPORT_EXCEL: 'ORGANIZATION_COMPANY_IMPORT_EXCEL',
  ORG_COMPANY_EXPORT_EXCEL: 'ORGANIZATION_COMPANY_EXPORT_EXCEL',

  // ORGANIZATION - BRANCH
  ORG_BRANCH_VIEW: 'ORGANIZATION_BRANCH_VIEW',
  ORG_BRANCH_MANAGE: 'ORGANIZATION_BRANCH_MANAGE',
  ORG_BRANCH_CREATE: 'ORGANIZATION_BRANCH_CREATE',
  ORG_BRANCH_UPDATE: 'ORGANIZATION_BRANCH_UPDATE',
  ORG_BRANCH_DEACTIVATE: 'ORGANIZATION_BRANCH_DEACTIVATE',
  ORG_BRANCH_ACTIVATE: 'ORGANIZATION_BRANCH_ACTIVATE',
  ORG_BRANCH_IMPORT_EXCEL: 'ORGANIZATION_BRANCH_IMPORT_EXCEL',
  ORG_BRANCH_EXPORT_EXCEL: 'ORGANIZATION_BRANCH_EXPORT_EXCEL',

  // ORGANIZATION - DEPARTMENT
  ORG_DEPARTMENT_VIEW: 'ORGANIZATION_DEPARTMENT_VIEW',
  ORG_DEPARTMENT_MANAGE: 'ORGANIZATION_DEPARTMENT_MANAGE',
  ORG_DEPARTMENT_CREATE: 'ORGANIZATION_DEPARTMENT_CREATE',
  ORG_DEPARTMENT_UPDATE: 'ORGANIZATION_DEPARTMENT_UPDATE',
  ORG_DEPARTMENT_DEACTIVATE: 'ORGANIZATION_DEPARTMENT_DEACTIVATE',
  ORG_DEPARTMENT_ACTIVATE: 'ORGANIZATION_DEPARTMENT_ACTIVATE',
  ORG_DEPARTMENT_IMPORT_EXCEL: 'ORGANIZATION_DEPARTMENT_IMPORT_EXCEL',
  ORG_DEPARTMENT_EXPORT_EXCEL: 'ORGANIZATION_DEPARTMENT_EXPORT_EXCEL',

  // ORGANIZATION - PART
  ORG_PART_VIEW: 'ORGANIZATION_PART_VIEW',
  ORG_PART_MANAGE: 'ORGANIZATION_PART_MANAGE',
  ORG_PART_CREATE: 'ORGANIZATION_PART_CREATE',
  ORG_PART_UPDATE: 'ORGANIZATION_PART_UPDATE',
  ORG_PART_DEACTIVATE: 'ORGANIZATION_PART_DEACTIVATE',
  ORG_PART_ACTIVATE: 'ORGANIZATION_PART_ACTIVATE',
  ORG_PART_IMPORT_EXCEL: 'ORGANIZATION_PART_IMPORT_EXCEL',
  ORG_PART_EXPORT_EXCEL: 'ORGANIZATION_PART_EXPORT_EXCEL',

  // ORGANIZATION - PART_MASTER
  ORG_PART_MASTER_VIEW: 'ORGANIZATION_PART_MASTER_VIEW',
  ORG_PART_MASTER_MANAGE: 'ORGANIZATION_PART_MASTER_MANAGE',
  ORG_PART_MASTER_CREATE: 'ORGANIZATION_PART_MASTER_CREATE',
  ORG_PART_MASTER_UPDATE: 'ORGANIZATION_PART_MASTER_UPDATE',
  ORG_PART_MASTER_DEACTIVATE: 'ORGANIZATION_PART_MASTER_DEACTIVATE',
  ORG_PART_MASTER_ACTIVATE: 'ORGANIZATION_PART_MASTER_ACTIVATE',
  ORG_PART_MASTER_IMPORT_EXCEL: 'ORGANIZATION_PART_MASTER_IMPORT_EXCEL',
  ORG_PART_MASTER_EXPORT_EXCEL: 'ORGANIZATION_PART_MASTER_EXPORT_EXCEL',

  // ORGANIZATION - POSITION
  ORG_POSITION_VIEW: 'ORGANIZATION_POSITION_VIEW',
  ORG_POSITION_MANAGE: 'ORGANIZATION_POSITION_MANAGE',
  ORG_POSITION_CREATE: 'ORGANIZATION_POSITION_CREATE',
  ORG_POSITION_UPDATE: 'ORGANIZATION_POSITION_UPDATE',
  ORG_POSITION_DEACTIVATE: 'ORGANIZATION_POSITION_DEACTIVATE',
  ORG_POSITION_ACTIVATE: 'ORGANIZATION_POSITION_ACTIVATE',
  ORG_POSITION_IMPORT_EXCEL: 'ORGANIZATION_POSITION_IMPORT_EXCEL',
  ORG_POSITION_EXPORT_EXCEL: 'ORGANIZATION_POSITION_EXPORT_EXCEL',

  // ORGANIZATION - POSITION_MASTER
  ORG_POSITION_MASTER_VIEW: 'ORGANIZATION_POSITION_MASTER_VIEW',
  ORG_POSITION_MASTER_MANAGE: 'ORGANIZATION_POSITION_MASTER_MANAGE',
  ORG_POSITION_MASTER_CREATE: 'ORGANIZATION_POSITION_MASTER_CREATE',
  ORG_POSITION_MASTER_UPDATE: 'ORGANIZATION_POSITION_MASTER_UPDATE',
  ORG_POSITION_MASTER_DEACTIVATE: 'ORGANIZATION_POSITION_MASTER_DEACTIVATE',
  ORG_POSITION_MASTER_ACTIVATE: 'ORGANIZATION_POSITION_MASTER_ACTIVATE',
  ORG_POSITION_MASTER_IMPORT_EXCEL: 'ORGANIZATION_POSITION_MASTER_IMPORT_EXCEL',
  ORG_POSITION_MASTER_EXPORT_EXCEL: 'ORGANIZATION_POSITION_MASTER_EXPORT_EXCEL',

  // ── HUMAN RESOURCE ────────────────────────────────────────
  HR_VIEW: 'HUMAN_RESOURCE_VIEW',
  HR_MANAGE: 'HUMAN_RESOURCE_MANAGE',

  // HR - EMPLOYEE
  HR_EMPLOYEE_VIEW: 'HUMAN_RESOURCE_EMPLOYEE_VIEW',
  HR_EMPLOYEE_MANAGE: 'HUMAN_RESOURCE_EMPLOYEE_MANAGE',
  HR_EMPLOYEE_CREATE: 'HUMAN_RESOURCE_EMPLOYEE_CREATE',
  HR_EMPLOYEE_UPDATE: 'HUMAN_RESOURCE_EMPLOYEE_UPDATE',
  HR_EMPLOYEE_DEACTIVATE: 'HUMAN_RESOURCE_EMPLOYEE_DEACTIVATE',
  HR_EMPLOYEE_ACTIVATE: 'HUMAN_RESOURCE_EMPLOYEE_ACTIVATE',
  HR_EMPLOYEE_IMPORT_EXCEL: 'HUMAN_RESOURCE_EMPLOYEE_IMPORT_EXCEL',
  HR_EMPLOYEE_EXPORT_EXCEL: 'HUMAN_RESOURCE_EMPLOYEE_EXPORT_EXCEL',

  // HR - CONTRACT_TYPE
  HR_CONTRACT_TYPE_VIEW: 'HUMAN_RESOURCE_CONTRACT_TYPE_VIEW',
  HR_CONTRACT_TYPE_MANAGE: 'HUMAN_RESOURCE_CONTRACT_TYPE_MANAGE',
  HR_CONTRACT_TYPE_CREATE: 'HUMAN_RESOURCE_CONTRACT_TYPE_CREATE',
  HR_CONTRACT_TYPE_UPDATE: 'HUMAN_RESOURCE_CONTRACT_TYPE_UPDATE',
  HR_CONTRACT_TYPE_DEACTIVATE: 'HUMAN_RESOURCE_CONTRACT_TYPE_DEACTIVATE',
  HR_CONTRACT_TYPE_ACTIVATE: 'HUMAN_RESOURCE_CONTRACT_TYPE_ACTIVATE',

  // HR - CONTRACT
  HR_CONTRACT_VIEW: 'HUMAN_RESOURCE_CONTRACT_VIEW',
  HR_CONTRACT_MANAGE: 'HUMAN_RESOURCE_CONTRACT_MANAGE',
  HR_CONTRACT_CREATE: 'HUMAN_RESOURCE_CONTRACT_CREATE',
  HR_CONTRACT_UPDATE: 'HUMAN_RESOURCE_CONTRACT_UPDATE',
  HR_CONTRACT_SIGN: 'HUMAN_RESOURCE_CONTRACT_SIGN',
  HR_CONTRACT_TERMINATE: 'HUMAN_RESOURCE_CONTRACT_TERMINATE',
  HR_CONTRACT_RENEW: 'HUMAN_RESOURCE_CONTRACT_RENEW',

  // HR - REVIEW_RENEWAL
  HR_REVIEW_RENEWAL_VIEW: 'HUMAN_RESOURCE_REVIEW_RENEWAL_VIEW',
  HR_REVIEW_RENEWAL_MANAGE: 'HUMAN_RESOURCE_REVIEW_RENEWAL_MANAGE',
  HR_REVIEW_RENEWAL_CREATE: 'HUMAN_RESOURCE_REVIEW_RENEWAL_CREATE',
  HR_REVIEW_RENEWAL_UPDATE: 'HUMAN_RESOURCE_REVIEW_RENEWAL_UPDATE',
  HR_REVIEW_RENEWAL_APPROVE: 'HUMAN_RESOURCE_REVIEW_RENEWAL_APPROVE',
  HR_REVIEW_RENEWAL_REJECT: 'HUMAN_RESOURCE_REVIEW_RENEWAL_REJECT',
  HR_REVIEW_RENEWAL_APPLY: 'HUMAN_RESOURCE_REVIEW_RENEWAL_APPLY',

  // HR - TRANSFER
  HR_TRANSFER_VIEW: 'HUMAN_RESOURCE_TRANSFER_VIEW',
  HR_TRANSFER_MANAGE: 'HUMAN_RESOURCE_TRANSFER_MANAGE',
  HR_TRANSFER_CREATE: 'HUMAN_RESOURCE_TRANSFER_CREATE',
  HR_TRANSFER_UPDATE: 'HUMAN_RESOURCE_TRANSFER_UPDATE',
  HR_TRANSFER_APPROVE: 'HUMAN_RESOURCE_TRANSFER_APPROVE',
  HR_TRANSFER_REJECT: 'HUMAN_RESOURCE_TRANSFER_REJECT',
  HR_TRANSFER_APPLY: 'HUMAN_RESOURCE_TRANSFER_APPLY',
  HR_TRANSFER_CANCEL: 'HUMAN_RESOURCE_TRANSFER_CANCEL',

  // ── OPERATE ───────────────────────────────────────────────
  OPERATE_VIEW: 'OPERATE_VIEW',
  OPERATE_MANAGE: 'OPERATE_MANAGE',

  // OPERATE - TIMEKEEPING_STANDARD
  OPERATE_TIMEKEEPING_STANDARD_VIEW: 'OPERATE_TIMEKEEPING_STANDARD_VIEW',
  OPERATE_TIMEKEEPING_STANDARD_MANAGE: 'OPERATE_TIMEKEEPING_STANDARD_MANAGE',
  OPERATE_TIMEKEEPING_STANDARD_CREATE: 'OPERATE_TIMEKEEPING_STANDARD_CREATE',
  OPERATE_TIMEKEEPING_STANDARD_UPDATE: 'OPERATE_TIMEKEEPING_STANDARD_UPDATE',
  OPERATE_TIMEKEEPING_STANDARD_DEACTIVATE: 'OPERATE_TIMEKEEPING_STANDARD_DEACTIVATE',
  OPERATE_TIMEKEEPING_STANDARD_ACTIVATE: 'OPERATE_TIMEKEEPING_STANDARD_ACTIVATE',

  // OPERATE - TIMEKEEPING
  OPERATE_TIMEKEEPING_VIEW: 'OPERATE_TIMEKEEPING_VIEW',
  OPERATE_TIMEKEEPING_MANAGE: 'OPERATE_TIMEKEEPING_MANAGE',
  OPERATE_TIMEKEEPING_ADJUST: 'OPERATE_TIMEKEEPING_ADJUST',
  OPERATE_TIMEKEEPING_SUMMARIZE: 'OPERATE_TIMEKEEPING_SUMMARIZE',

  // OPERATE - ATTENDANCE_COMPLAINT
  OPERATE_ATTENDANCE_COMPLAINT_VIEW: 'OPERATE_ATTENDANCE_COMPLAINT_VIEW',
  OPERATE_ATTENDANCE_COMPLAINT_MANAGE: 'OPERATE_ATTENDANCE_COMPLAINT_MANAGE',
  OPERATE_ATTENDANCE_COMPLAINT_CREATE: 'OPERATE_ATTENDANCE_COMPLAINT_CREATE',
  OPERATE_ATTENDANCE_COMPLAINT_REVIEW: 'OPERATE_ATTENDANCE_COMPLAINT_REVIEW',

  // OPERATE - DAY_OFF_CONFIG
  OPERATE_DAY_OFF_CONFIG_VIEW: 'OPERATE_DAY_OFF_CONFIG_VIEW',
  OPERATE_DAY_OFF_CONFIG_MANAGE: 'OPERATE_DAY_OFF_CONFIG_MANAGE',
  OPERATE_DAY_OFF_CONFIG_CREATE: 'OPERATE_DAY_OFF_CONFIG_CREATE',
  OPERATE_DAY_OFF_CONFIG_UPDATE: 'OPERATE_DAY_OFF_CONFIG_UPDATE',
  OPERATE_DAY_OFF_CONFIG_DEACTIVATE: 'OPERATE_DAY_OFF_CONFIG_DEACTIVATE',
  OPERATE_DAY_OFF_CONFIG_ACTIVATE: 'OPERATE_DAY_OFF_CONFIG_ACTIVATE',

  // OPERATE - PUBLIC_HOLIDAY
  OPERATE_PUBLIC_HOLIDAY_VIEW: 'OPERATE_PUBLIC_HOLIDAY_VIEW',
  OPERATE_PUBLIC_HOLIDAY_MANAGE: 'OPERATE_PUBLIC_HOLIDAY_MANAGE',
  OPERATE_PUBLIC_HOLIDAY_CREATE: 'OPERATE_PUBLIC_HOLIDAY_CREATE',
  OPERATE_PUBLIC_HOLIDAY_UPDATE: 'OPERATE_PUBLIC_HOLIDAY_UPDATE',
  OPERATE_PUBLIC_HOLIDAY_DEACTIVATE: 'OPERATE_PUBLIC_HOLIDAY_DEACTIVATE',
  OPERATE_PUBLIC_HOLIDAY_ACTIVATE: 'OPERATE_PUBLIC_HOLIDAY_ACTIVATE',

  // OPERATE - LEAVE
  OPERATE_LEAVE_VIEW: 'OPERATE_LEAVE_VIEW',
  OPERATE_LEAVE_MANAGE: 'OPERATE_LEAVE_MANAGE',
  OPERATE_LEAVE_CREATE: 'OPERATE_LEAVE_CREATE',
  OPERATE_LEAVE_APPROVE: 'OPERATE_LEAVE_APPROVE',
  OPERATE_LEAVE_REJECT: 'OPERATE_LEAVE_REJECT',
  OPERATE_LEAVE_CANCEL: 'OPERATE_LEAVE_CANCEL',

  // OPERATE - LEAVE_ALLOCATION
  OPERATE_LEAVE_ALLOCATION_VIEW: 'OPERATE_LEAVE_ALLOCATION_VIEW',
  OPERATE_LEAVE_ALLOCATION_MANAGE: 'OPERATE_LEAVE_ALLOCATION_MANAGE',
  OPERATE_LEAVE_ALLOCATION_CREATE: 'OPERATE_LEAVE_ALLOCATION_CREATE',
  OPERATE_LEAVE_ALLOCATION_UPDATE: 'OPERATE_LEAVE_ALLOCATION_UPDATE',

  // OPERATE - SHIFT
  OPERATE_SHIFT_VIEW: 'OPERATE_SHIFT_VIEW',
  OPERATE_SHIFT_MANAGE: 'OPERATE_SHIFT_MANAGE',
  OPERATE_SHIFT_CREATE: 'OPERATE_SHIFT_CREATE',
  OPERATE_SHIFT_UPDATE: 'OPERATE_SHIFT_UPDATE',
  OPERATE_SHIFT_DEACTIVATE: 'OPERATE_SHIFT_DEACTIVATE',
  OPERATE_SHIFT_ACTIVATE: 'OPERATE_SHIFT_ACTIVATE',

  // OPERATE - WORK_SCHEDULE
  OPERATE_WORK_SCHEDULE_VIEW: 'OPERATE_WORK_SCHEDULE_VIEW',
  OPERATE_WORK_SCHEDULE_MANAGE: 'OPERATE_WORK_SCHEDULE_MANAGE',
  OPERATE_WORK_SCHEDULE_CREATE: 'OPERATE_WORK_SCHEDULE_CREATE',
  OPERATE_WORK_SCHEDULE_UPDATE: 'OPERATE_WORK_SCHEDULE_UPDATE',
  OPERATE_WORK_SCHEDULE_DEACTIVATE: 'OPERATE_WORK_SCHEDULE_DEACTIVATE',

  // OPERATE - WORK_PATTERN
  OPERATE_WORK_PATTERN_VIEW: 'OPERATE_WORK_PATTERN_VIEW',
  OPERATE_WORK_PATTERN_MANAGE: 'OPERATE_WORK_PATTERN_MANAGE',
  OPERATE_WORK_PATTERN_CREATE: 'OPERATE_WORK_PATTERN_CREATE',
  OPERATE_WORK_PATTERN_UPDATE: 'OPERATE_WORK_PATTERN_UPDATE',
  OPERATE_WORK_PATTERN_DEACTIVATE: 'OPERATE_WORK_PATTERN_DEACTIVATE',
  OPERATE_WORK_PATTERN_BULK_ASSIGN: 'OPERATE_WORK_PATTERN_BULK_ASSIGN',

  // ── PAYROLL ───────────────────────────────────────────────────────
  PAYROLL_VIEW: 'PAYROLL_VIEW',
  PAYROLL_MANAGE: 'PAYROLL_MANAGE',

  // PAYROLL - SALARY RUN
  PAYROLL_SALARY_VIEW: 'PAYROLL_SALARY_VIEW',
  PAYROLL_SALARY_MANAGE: 'PAYROLL_SALARY_MANAGE',
  PAYROLL_SALARY_CREATE: 'PAYROLL_SALARY_CREATE',
  PAYROLL_SALARY_UPDATE: 'PAYROLL_SALARY_UPDATE',
  PAYROLL_SALARY_APPROVE: 'PAYROLL_SALARY_APPROVE',
  PAYROLL_SALARY_MARK_PAID: 'PAYROLL_SALARY_MARK_PAID',
  PAYROLL_SALARY_CANCEL: 'PAYROLL_SALARY_CANCEL',

  // PAYROLL - CONFIG
  PAYROLL_CONFIG_VIEW: 'PAYROLL_CONFIG_VIEW',
  PAYROLL_CONFIG_MANAGE: 'PAYROLL_CONFIG_MANAGE',
  PAYROLL_CONFIG_CREATE: 'PAYROLL_CONFIG_CREATE',
  PAYROLL_CONFIG_UPDATE: 'PAYROLL_CONFIG_UPDATE',
  PAYROLL_CONFIG_DEACTIVATE: 'PAYROLL_CONFIG_DEACTIVATE',
  PAYROLL_CONFIG_ACTIVATE: 'PAYROLL_CONFIG_ACTIVATE',

  // ── SYSTEM / ROLE MANAGER ─────────────────────────────────────────
  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_MANAGE: 'ROLE_MANAGE',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',

  USER_VIEW: 'USER_VIEW',
  USER_MANAGE: 'USER_MANAGE',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',

  ACTION_LOG_VIEW: 'ACTION_LOG_VIEW',

  // ── MOBILE ────────────────────────────────────────────────────────
  MOBILE_ACCESS: 'MOBILE_ACCESS',
} as const satisfies Record<string, PermissionCode>;
